# Generated by Django 3.2 on 2024-06-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('password', models.CharField(default='123456', max_length=255, verbose_name='密码')),
            ],
        ),
    ]
