# Generated by Django 3.2 on 2024-06-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='nick_name',
            field=models.CharField(default='Admin', max_length=255, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='phone',
            field=models.CharField(max_length=32, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
