# Generated by Django 3.2 on 2024-06-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20240622_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='avatar',
            field=models.CharField(max_length=256, null=True, verbose_name='用户头像'),
        ),
    ]
