# Generated by Django 3.2 on 2024-06-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_adminuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': '管理员表', 'verbose_name_plural': '管理员表'},
        ),
        migrations.AlterModelTable(
            name='adminuser',
            table='admin_user',
        ),
    ]
