# Generated by Django 3.2 on 2024-06-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MallUser',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('phone', models.CharField(max_length=32, null=True, verbose_name='手机号')),
                ('sex', models.BooleanField(null=True, verbose_name='性别')),
                ('header_img', models.CharField(max_length=256, null=True, verbose_name='用户头像')),
            ],
            options={
                'verbose_name': '商城用户',
                'verbose_name_plural': '商城用户',
                'db_table': 'mall_user',
            },
        ),
    ]
