# Generated by Django 3.2 on 2024-06-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malluser',
            old_name='header_img',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='malluser',
            name='nick_name',
            field=models.CharField(default='user', max_length=256, null=True, verbose_name='用户名称'),
        ),
    ]
