# Generated by Django 3.2.21 on 2024-06-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supplier',
            table='suppliers',
        ),
        migrations.AlterModelTable(
            name='supplierproduct',
            table='supplier_products',
        ),
    ]
